name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build&Deploy template-site"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ekbtrees-admin-frontend:latest
          secrets: |
            "ASPNETCORE_ENVIRONMENT=Release"
          build-args: |
            build_mode=Release

  redeploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-docker-image]
    steps:
      - name: "Run deploy on server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            ls -la
            docker-compose pull
            docker-compose up -d
